# Generated by Django 4.1.5 on 2023-02-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinates',
            new_name='Map',
        ),
    ]
