# Generated by Django 3.2.19 on 2023-11-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo_pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_r', models.FileField(upload_to=gallery.models.user_right_image_path)),
                ('image_l', models.FileField(upload_to=gallery.models.user_left_image_path)),
                ('index', models.IntegerField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_photo', to='gallery.location')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.FloatField()),
                ('center_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StreetObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('objtype', models.CharField(choices=[('postacion', 'Postacion'), ('luminaria', 'Luminaria'), ('propiedades', 'Propiedades'), ('otros', 'Otros')], default='otros', max_length=20, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_object', to='gallery.location')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='gallery.photo_pair')),
                ('photoset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_streetobject', to='gallery.photoset')),
                ('roi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roi_object', to='gallery.roi')),
            ],
        ),
        migrations.AddField(
            model_name='photo_pair',
            name='photoset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='gallery.photoset'),
        ),
        migrations.CreateModel(
            name='ParametersPhotoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusDetection', models.CharField(max_length=100, null=True)),
                ('tasksId', models.CharField(max_length=200, null=True)),
                ('countLuminaria', models.IntegerField()),
                ('countPostacion', models.IntegerField()),
                ('countVehiculos', models.IntegerField()),
                ('countOtros', models.IntegerField()),
                ('lastPhotoDetect', models.IntegerField()),
                ('photoset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumParamters', to='gallery.photoset')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.CharField(max_length=200)),
                ('attribute_value', models.CharField(max_length=200)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_object', to='gallery.streetobject')),
            ],
        ),
    ]
