# Generated by Django 4.1.5 on 2023-05-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetobject',
            name='roi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roi_object', to='gallery.roi'),
        ),
        migrations.CreateModel(
            name='ObjectAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.CharField(max_length=200)),
                ('attribute_value', models.CharField(max_length=200)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_object', to='gallery.streetobject')),
            ],
        ),
    ]
