# Generated by Django 3.2.19 on 2023-10-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_parametersphotoset'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetobject',
            name='photoset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_streetobject', to='gallery.photoset'),
        ),
    ]
