# Generated by Django 3.2.19 on 2023-10-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_streetobject_photoset'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersphotoset',
            name='statusDetection',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
