# Generated by Django 3.2.19 on 2023-11-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_parametersphotoset_tasksid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetobject',
            name='objtype',
            field=models.CharField(choices=[('postacion', 'Postacion'), ('luminaria', 'Luminaria'), ('propiedades', 'Propiedades'), ('otros', 'Otros')], default='otros', max_length=20, null=True),
        ),
    ]
